#!/bin/bash

plus=$("=")

read -p "Masukan Url (ex:vmess://xxx) : " link
$link$plus > /tmp/tjn.yaml


name1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1')
address1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d'&' -f3 | cut -b 6-30)
port1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d: -f3 | cut -d/ -f1)
type1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1')
password1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d@ -f1 | cut -b 10-45)
network1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d'&' -f2 | cut -b 6-10)
path1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d= -f5 | sed 's/%2F/'/'')
host1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d'&' -f3 | cut -b 6-30)



printout(){
echo -e "proxies: "
echo -e "- name: $name1"
echo -e "  type: $type1"
echo -e "  server: $host1"
echo -e "  port: $port1"
echo -e "  password: $password1"
echo -e "  sni: isi sendiri(bug/domain)"
echo -e "  skip-cert-verify: true"
echo -e "  network: $network1"
echo -e "  ws-opts:"
echo -e "    path: $path1"
echo -e "    headers:"
echo -e "      Host: $host1"
echo -e "  udp: true"


}


printout > /etc/openclash/trojan.yaml
rm /tmp/tjn.yaml
/sbin/tools
