#!/bin/bash
# This Script by Alkhanet (http://github.com/alkhanet26)

  function ws(){
	#plus=$('#')
	name1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1')
	address1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d@ -f2 | cut -d: -f1)
	port1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d: -f3 | cut -d/ -f1 | cut -d? -f1)
	type1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1' | cut -d'-' -f1)
	password1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d@ -f1 | cut -d/ -f3)
	network1=$(cat /tmp/tjn.yaml | awk -F 'type=' '{print $2}' | cut -d'&' -f1 | cut -d'#' -f1)
	path1=$(cat /tmp/tjn.yaml | awk -F 'path=' '{print $2}' | sed 's+%2F+/+g' | cut -d'&' -f1 | cut -d# -f1)
	host1=$(cat /tmp/tjn.yaml | awk -F 'host=' '{print $2}' | cut -d'&' -f1)
	bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)

	printoutws(){
	echo -e "proxies: "
	echo -e "- name: $name1-$network1"
	echo -e "  type: $type1"
	echo -e "  server: $host1"
	echo -e "  port: $port1"
	echo -e "  password: $password1"
	echo -e "  sni: $bug1"
	echo -e "  skip-cert-verify: true"
	echo -e "  network: $network1"
	echo -e "  ws-opts:"
	echo -e "    path: $path1"
	echo -e "    headers:"
	echo -e "      Host: $host1"
	echo -e "  udp: true"
	}
	printoutws > /etc/openclash/trojan.yaml
	/sbin/tools
  }

  function wsr(){
	#plus=$('#')
	name1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1')
	address1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d@ -f2 | cut -d: -f1)
	port1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d: -f3 | cut -d/ -f1 | cut -d? -f1)
	type1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1' | cut -d'-' -f1)
	password1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d@ -f1 | cut -d/ -f3)
	network1=$(cat /tmp/tjn.yaml | awk -F 'type=' '{print $2}' | cut -d'&' -f1 | cut -d'#' -f1)
	path1=$(cat /tmp/tjn.yaml | awk -F 'path=' '{print $2}' | sed 's+%2F+/+g' | cut -d'&' -f1 | cut -d# -f1)
	host1=$(cat /tmp/tjn.yaml | awk -F 'host=' '{print $2}' | cut -d'&' -f1)
	bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)

	printoutwsr(){
	echo -e "proxies: "
	echo -e "- name: $name1-$network1"
	echo -e "  type: $type1"
	echo -e "  server: $bug1"
	echo -e "  port: $port1"
	echo -e "  password: $password1"
	echo -e "  sni: $host1"
	echo -e "  skip-cert-verify: true"
	echo -e "  network: $network1"
	echo -e "  ws-opts:"
	echo -e "    path: $path1"
	echo -e "    headers:"
	echo -e "      Host: $host1"
	echo -e "  udp: true"
	}
	printoutwsr > /etc/openclash/trojan.yaml
	/sbin/tools

  }

  function gfw(){
	#plus=$('#')
	name1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1')
	address1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d@ -f2 | cut -d: -f1)
	port1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d: -f3 | cut -d/ -f1 | cut -d? -f1)
	type1=$(cat /tmp/tjn.yaml | grep trojan | cut -d: -f1| awk 'NR==1' | cut -d'-' -f1)
	password1=$(cat /tmp/tjn.yaml | grep trojan /tmp/tjn.yaml | cut -d@ -f1 | cut -d/ -f3)
	bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)


	printoutgfw(){
	echo -e "proxies: "
	echo -e "- name: $name1-gfw"
	echo -e "  type: $type1"
	echo -e "  server: $address1"
	echo -e "  port: $port1"
	echo -e "  password: $password1"
	echo -e "  skip-cert-verify: true"
	echo -e "  sni: $bug1"
	echo -e "  udp: true"
	}
	printoutgfw > /etc/openclash/trojan.yaml
	/sbin/tools
  }

read -p "Masukan Bug provider (host/ip) : " b
echo -e "b="$b > /tmp/bugs
clear
read -p "Masukan Url (ex:trojan://xxx) : " link
echo $link > /tmp/tjn.yaml
jenis1=$(cat /tmp/tjn.yaml | awk -F 'type=' '{print $2}' | cut -d'&' -f1 | cut -d'#' -f1)

if [[ "$jenis1" = "ws" ]]; then
	read -p "Reverse Mode : (y/n)" an
	if [[ $an == "y" || $an == "Y" ]]; then
	wsr
	else
	ws
	fi
else
gfw
fi
