#!/bin/bash



{
opkg update && opkg install node-npm python3 python3-pip
npm -g install v2ray-tools && pip install json2yaml && npm audit fix --force && pip install --upgrade ppip
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/convms/main/tools" -O /sbin/tools && chmod 7777 /sbin/tools
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/convms/main/vmess" -O /sbin/vmess && chmod 7777 /sbin/vmess
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/convms/main/base.json" -O /usr/lib/node_modules/v2ray-tools/src/base.json && chmod 644 /usr/lib/node_modules/v2ray-tools/src/base.json
}
