#!/bin/bash
#This script by AlkhaNET (http://github.com/alkhanet26)
# VERSION ALPHA 2.7


{
echo "Checking Version"
sleep 3
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/convms/main/versi_yaml" -O /tmp/versi_yaml && chmod +x /tmp/versi_yaml
clear
an=$(grep -o 'VERSION 2.7' /tmp/versi_yaml | awk -F 'VERSION ' '{print $2}' | cut -d' ' -f1 | awk 'NR==1')
in=$(grep -o 'VERSION ALPHA 2.7' /sbin/tools | awk -F 'VERSION ALPHA ' '{print $2}' | cut -d' ' -f1 | awk 'NR==1')
if [[ $an == $in ]]; then
clear
echo -e "YAML Converter Sudah Versi Terbaru "$in
echo -e "Kembali Ke Menu Awal"
sleep 5
rm /tmp/versi_yaml
/sbin/tools
else
echo -e "Updating YAML Converter"
sleep 1
clear
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/convms/main/update" -O /sbin/update && chmod 777 /sbin/update
wget --no-check-certificate "https://raw.githubusercontent.com/alkhanet26/convms/main/tools" -O /sbin/tools && chmod 777 /sbin/tools
clear
sleep 2
rm /tmp/versi_yaml
/sbin/tools up
fi
}
