#!/bin/bash
# This Script by Alkhanet (http://github.com/alkhanet26)


	function ws(){
	 name1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d# -f2)
	 address1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d@ -f2 | cut -d: -f1)
	 port1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d: -f3 | cut -d/ -f1 | cut -d? -f1)
	 type1=$(cat /tmp/vls.yaml | grep vless | cut -d: -f1| awk 'NR==1')
	 uuid1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d@ -f1 | cut -b 10-45)
	 tls1=$(cat /tmp/vls.yaml | grep vless | cut -d= -f3 | cut -d'&' -f1 | sed 's+tls+true+g' | sed 's+none+false+g')
	 network1=$(cat /tmp/vls.yaml | awk -F 'type=' '{print $2}' < /tmp/vls.yaml | cut -d'&' -f1 | cut -d# -f1)
	 path1=$(cat /tmp/vls.yaml | awk -F 'path=' '{print $2}' < /tmp/vls.yaml | sed 's+%2F+/+g' | sed 's+%2f+/+g' | sed 's+%3F+/+g' | sed 's+%3f+/+g' | sed 's+%3D+/+g' | sed 's+%3d+/+g' | cut -d'&' -f1 | cut -d# -f1)
	 host1=$(cat /tmp/vls.yaml | awk -F 'host=' '{print $2}' < /tmp/vls.yaml | cut -d'&' -f1)
	 #petik=$(cat /tmp/vls.yaml | grep -o : | awk 'NR==1' | sed 's+:+"+g')
	 bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)

	 printoutws(){
	 echo -e "proxies: "
	 echo -e "- name: $name1"
	 echo -e "  type: $type1"
	 echo -e "  server: $address1"
	 echo -e "  port: $port1"
	 echo -e "  uuid: $uuid1"
	 echo -e "  skip-cert-verify: true"
	 echo -e "  tls: $tls1"
	 echo -e "  servername: $bug1"
	 echo -e "  network: $network1"
	 echo -e "  ws-opts:"
	 echo -e "    path: $path1"
	 echo -e "    headers:"
	 echo -e "      Host: $address1"
	 echo -e "  udp: true"
	 }
	 printoutws > /etc/openclash/vless.yaml
	 /tmp/vls.yaml
	 /sbin/tools
	}

	function wsr(){
	 name1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d# -f2)
	 address1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d@ -f2 | cut -d: -f1)
	 port1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d: -f3 | cut -d/ -f1 | cut -d? -f1)
	 type1=$(cat /tmp/vls.yaml | grep vless | cut -d: -f1| awk 'NR==1')
	 uuid1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d@ -f1 | cut -b 10-45)
	 tls1=$(cat /tmp/vls.yaml | grep vless | cut -d= -f3 | cut -d'&' -f1 | sed 's+tls+true+g' | sed 's+none+false+g')
	 network1=$(cat /tmp/vls.yaml | awk -F 'type=' '{print $2}' < /tmp/vls.yaml | cut -d'&' -f1 | cut -d# -f1)
	 path1=$(cat /tmp/vls.yaml | awk -F 'path=' '{print $2}' < /tmp/vls.yaml | sed 's+%2F+/+g' | sed 's+%2f+/+g' | sed 's+%3F+/+g' | sed 's+%3f+/+g' | sed 's+%3D+/+g' | sed 's+%3d+/+g' | cut -d'&' -f1 | cut -d# -f1)
	 host1=$(cat /tmp/vls.yaml | awk -F 'host=' '{print $2}' < /tmp/vls.yaml | cut -d'&' -f1)
	 #petik=$(cat /tmp/vls.yaml | grep -o : | awk 'NR==1' | sed 's+:+"+g')
	 bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)

	 printoutwsr(){
	 echo -e "proxies: "
	 echo -e "- name: $name1"
	 echo -e "  type: $type1"
	 echo -e "  server: $bug1"
	 echo -e "  port: $port1"
	 echo -e "  uuid: $uuid1"
	 echo -e "  skip-cert-verify: true"
	 echo -e "  tls: $tls1"
	 echo -e "  servername: $address1"
	 echo -e "  network: $network1"
	 echo -e "  ws-opts:"
	 echo -e "    path: $path1"
	 echo -e "    headers:"
	 echo -e "      Host: $address1"
	 echo -e "  udp: true"
	 }
	 printoutwsr > /etc/openclash/vless.yaml
	 /tmp/vls.yaml
	 /sbin/tools
	}



read -p "Masukan Bug provider (host/ip) : " b
echo -e "b="$b > /tmp/bugs
clear
read -p "Masukan Url (ex:vless://xxx) : " link
echo $link > /tmp/vls.yaml
jenis1=$(cat /tmp/vls.yaml | awk -F 'type=' '{print $2}' < /tmp/vls.yaml | cut -d'&' -f1 | cut -d# -f1)

if [[ "$jenis1" = "ws" ]]; then
	read -p "Reverse Mode : (y/n)" an
	if [[ $an == "y" || $an == "Y" ]]; then
	wsr
	else
	ws
	fi
fi

