#!/bin/bash
# This Script by Alkhanet (http://github.com/alkhanet26)


read -p "Masukan Url (ex:vless://xxx) : " link
echo $link > /tmp/vls.yaml

name1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d# -f2)
address1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d@ -f2 | cut -d: -f1)
port1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d: -f3 | cut -d/ -f1 | cut -d? -f1)
type1=$(cat /tmp/vls.yaml | grep vless | cut -d: -f1| awk 'NR==1')
uuid1=$(cat /tmp/vls.yaml | grep vless /tmp/vls.yaml | cut -d@ -f1 | cut -b 10-45)
network1=$(cat /tmp/vls.yaml | awk -F 'type=' '{print $2}' < /tmp/vls.yaml | cut -d'&' -f1 | cut -d# -f1)
path1=$(cat /tmp/vls.yaml | awk -F 'path=' '{print $2}' < /tmp/vls.yaml | sed 's+%2F+/+g' | sed 's+%2f+/+g' | sed 's+%3F+/+g' | sed 's+%3f+/+g' | sed 's+%3D+/+g' | sed 's+%3d+/+g' | cut -d'&' -f1 | cut -d# -f1)
host1=$(cat /tmp/vls.yaml | awk -F 'host=' '{print $2}' < /tmp/vls.yaml | cut -d'&' -f1)


printout(){
echo -e "proxies: "
echo -e "- name: $name1"
echo -e "  type: $type1"
echo -e "  server: $address1"
echo -e "  port: $port1"
echo -e "  uuid: $uuid1"
echo -e "  skip-cert-verify: true"
echo -e "  tls: isi sendiri(true/false)"
echo -e "  servername: isi sendiri(bug/domain)"
echo -e "  network: $network1"
echo -e "  ws-opts:"
echo -e "    path: $path1"
echo -e "    headers:"
echo -e "      Host: $host1"
echo -e "  udp: true"


}


printout > /etc/openclash/vless.yaml
rm /tmp/vls.yaml
/sbin/tools
