#!/bin/bash

#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE


# This Script by Vito Harhari (http://github.com/vitoharhari)
# Fix config clash.yaml by alkhanet (http://github.com/alkhanet26)

	function ws(){
	 name1=$(cat /tmp/cfgvms.json | grep tag | cut -d: -f2| cut -d_ -f1 | cut -d'"' -f2 | awk 'NR==2')
 	 address1=$(cat /tmp/cfgvms.json | grep address | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==2')
	 port1=$(cat /tmp/cfgvms.json | grep port | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==2')
	 #type1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==1')
	 uuid1=$(cat /tmp/cfgvms.json | grep '"id":' | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==1')
	 alterid1=$(cat /tmp/cfgvms.json | grep alterId | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 chiper1=$(cat /tmp/cfgvms.json | grep security | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 tls1=$(cat /tmp/cfgvms.json | grep security | cut -d: -f2| cut -d'"' -f2 | awk 'NR==2' | sed 's+tls+true+g' | sed 's+null,+false+g')
	 #skip1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 #servername1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 network1=$(cat /tmp/cfgvms.json | grep network | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 path1=$(cat /tmp/cfgvms.json | grep '"path": ' | awk 'NR==1' | cut -d'"' -f4)
	 host1=$(cat /tmp/cfgvms.json | grep Host | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 udp1=$(cat /tmp/cfgvms.json | grep udp | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1' | sed 's+,++g' )
	 #petik=$(cat /tmp/cfgvms.json | grep -o '"' | awk 'NR==1')
	 bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)

	 printoutws(){
	 echo ""
	 echo -e "- name : $name1"
	 echo -e "  server: $address1"
	 echo -e "  port:$port1"
 	 echo -e "  type: vmess"
	 echo -e "  uuid: $uuid1"
	 echo -e "  alterId:$alterid1"
	 echo -e "  cipher: $chiper1"
	 echo -e "  tls: $tls1"
	 echo -e "  skip-cert-verify: true"
	 echo -e "  servername: $bug1"
	 echo -e "  network: $network1"
	 echo -e "  ws-opts:"
	 echo -e "    path: $path1"
	 echo -e "    headers:"
	 echo -e "      Host: $host1"
	 echo -e "  udp:$udp1"
	 }
	 printoutws > /etc/openclash/vmess.yaml
	 #rm /tmp/cfgvms.json
 	 #/sbin/tools
	}

	function wsr(){
	 name1=$(cat /tmp/cfgvms.json | grep tag | cut -d: -f2| cut -d_ -f1 | cut -d'"' -f2 | awk 'NR==2')
 	 address1=$(cat /tmp/cfgvms.json | grep address | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==2')
	 port1=$(cat /tmp/cfgvms.json | grep port | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==2')
	 #type1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==1')
	 uuid1=$(cat /tmp/cfgvms.json | grep '"id":' | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==1')
	 alterid1=$(cat /tmp/cfgvms.json | grep alterId | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 chiper1=$(cat /tmp/cfgvms.json | grep security | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 tls1=$(cat /tmp/cfgvms.json | grep security | cut -d: -f2| cut -d'"' -f2 | awk 'NR==2' | sed 's+tls+true+g' | sed 's+null,+false+g')
	 #skip1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 #servername1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 network1=$(cat /tmp/cfgvms.json | grep network | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 path1=$(cat /tmp/cfgvms.json | grep '"path": ' | awk 'NR==1' | cut -d'"' -f4)
	 host1=$(cat /tmp/cfgvms.json | grep Host | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 udp1=$(cat /tmp/cfgvms.json | grep udp | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1' | sed 's+,++g' )
	 #petik=$(cat /tmp/cfgvms.json | grep -o '"' | awk 'NR==1')
	 bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)

	 printoutwsr(){
	 echo ""
	 echo -e "- name : $name1"
	 echo -e "  server: $bug1"
	 echo -e "  port:$port1"
 	 echo -e "  type: vmess"
	 echo -e "  uuid: $uuid1"
	 echo -e "  alterId:$alterid1"
	 echo -e "  cipher: $chiper1"
	 echo -e "  tls: $tls1"
	 echo -e "  skip-cert-verify: true"
	 echo -e "  servername: $address1"
	 echo -e "  network: $network1"
	 echo -e "  ws-opts:"
	 echo -e "    path: $path1"
	 echo -e "    headers:"
	 echo -e "      Host: $host1"
	 echo -e "  udp:$udp1"
	 }
	 printoutwsr > /etc/openclash/vmess.yaml
	 #rm /tmp/cfgvms.json && rm /tmp/cfgvms.json
 	 #/sbin/tools
	}

	function tcp(){
	 name1=$(cat /tmp/cfgvms.json | grep tag | cut -d: -f2| cut -d_ -f1 | cut -d'"' -f2 | awk 'NR==2')
 	 address1=$(cat /tmp/cfgvms.json | grep address | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==2')
	 port1=$(cat /tmp/cfgvms.json | grep port | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==2')
	 #type1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==1')
	 uuid1=$(cat /tmp/cfgvms.json | grep '"id":' | cut -d: -f2 | cut -d'"' -f2 | awk 'NR==1')
	 alterid1=$(cat /tmp/cfgvms.json | grep alterId | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 chiper1=$(cat /tmp/cfgvms.json | grep security | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 tls1=$(cat /tmp/cfgvms.json | grep security | cut -d: -f2| cut -d'"' -f2 | awk 'NR==2' | sed 's+tls+true+g' | sed 's+null,+false+g')
	 #skip1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 #servername1=$(cat /tmp/cfgvms.json | grep type | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 network1=$(cat /tmp/cfgvms.json | grep network | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 path1=$(cat /tmp/cfgvms.json | grep '"path": ' | awk 'NR==1' | cut -d'"' -f4)
	 host1=$(cat /tmp/cfgvms.json | grep Host | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1')
	 udp1=$(cat /tmp/cfgvms.json | grep udp | cut -d: -f2| cut -d'"' -f2 | awk 'NR==1' | sed 's+,++g' )
	 #petik=$(cat /tmp/cfgvms.json | grep -o '"' | awk 'NR==1')
	 bug1=$(grep '=' /tmp/bugs | cut -d'=' -f2)

	 printouttcp(){
	 echo ""
	 echo -e "- name : $name1"
	 echo -e "  server: $address1"
	 echo -e "  port:$port1"
 	 echo -e "  type: vmess"
	 echo -e "  uuid: $uuid1"
	 echo -e "  alterId:$alterid1"
	 echo -e "  cipher: $chiper1"
	 echo -e "  tls: $tls1"
	 echo -e "  skip-cert-verify: true"
	 echo -e "  servername: $bug1"
	 echo -e "  udp:$udp1"
	 }
	 printouttcp > /etc/openclash/vmess.yaml
	 #rm /tmp/cfgvms.json && rm /tmp/cfgvms.json
 	 #/sbin/tools
	}

function nginput(){
read -p "Masukan Bug provider (host/ip) : " b
echo -e "b="$b > /tmp/bugs
clear
read -p "Masukan Url (ex:vmess://xxx) : " link
v2ray-tools vmess2config --url $link > /tmp/cfgvms.json
jenis1=$(cat /tmp/cfgvms.json | grep "network" | cut -d: -f2 | cut -d'"' -f2| awk 'NR==1')

if [[ "$jenis1" = "ws" ]]; then
	read -p "Reverse Mode  (y/n) : " an
	if [[ $an == "y" || $an == "Y" ]]; then
	wsr
	else
	ws
	fi
else
tcp
fi

}

function ngexport(){
	read -p "Tambahkan otomatis config ke proxy_provider? (y/n) : " pp
	if [[ $pp == "y" || $pp == "Y" ]]; then
		echo ""
		echo -e "Berikut config yang ada di Proxy_provider"
		sleep 2
		echo -e "$R"
		ls /etc/openclash/proxy_provider/
		sleep 2
		echo -e "$Y"
		read -p "Masukan Nama Config di Proxy_Provider  (Contoh : alkhanet.yaml) : " nmcfg
		echo -e "Export to Proxy Provider, please wait..."
		
		resprox=$(cat /etc/openclash/proxy_provider/$nmcfg | grep -o proxies)
		if [[ $resprox == "proxies" ]]; then
		echo -e "$G"
		echo -e "Config Ditemukan!"
		else
		echo "proxies:" > /etc/openclash/proxy_provider/$nmcfg
		fi

		sleep 3
		cat /etc/openclash/vmess.yaml >> /etc/openclash/proxy_provider/$nmcfg
		sleep 1
		echo -e "$G"
		echo -e "config berhasil dimasukkan ke /etc/openclash/proxy_provider/$nmcfg"
		sleep 2
		echo -e "kembali ke halaman awal ..."
		sleep 2
		/sbin/tools
	else
	echo -e "kembali ke halaman awal ..."
	sleep 2
	/sbin/tools
	fi
}

nginput
ngexport
